export const footerLinks = [
  {
    title: "Shop",
    links: [
      { title: "Products", url: "/" },
      { title: "Overview", url: "/" },
      { title: "Pricing", url: "/" },
      { title: "Releases", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "About Us", url: "/" },
      { title: "Contact", url: "/" },
      { title: "News", url: "/" },
      { title: "Support", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];

export const categories = [
  {
    title: "Categories",
    name: ["All", "TV", "Audio", "Laptop", "Mobile", "Gaming", "Appliances"],
  },
  {
    title: "Brand",
    name: [
      "All",
      "Sony",
      "Panasonic",
      "Boat",
      "Mivi",
      "JBL",
      "Soundcore",
      "Marchall",
      "Bang & Olufsen",
      "Denon",
      "Apple",
      "Tilted Nation",
      "Wuqioei",
      "DIMU",
      "Generic",
      "Instant Pot",
      "ECOVACS",
      "Havells",
      "beatXP",
      "Morphy Richards",
      "Bajaj",
      "Wirpo",
      "Sarth Enterprise",
      "Eveready",
      "Sujata",
      "Faber",
      "Bosch",
      "Philips",
      "Voltas",
      "Eureka Forbes",
      "Godrej",
      "Anchor",
      "Asus",
      "Acer",
      "Jio",
      "Leveno",
      "MSI",
      "HP",
      "MI",
      "Realme",
      "Hp Victus",
      "Ant Esports",
      "Logitech G",
      "Hyperkin",
      "VGRASSP",
      "Nitho",
      "GIGABYTE",
      "iQOO",
      "Vivo",
      "Poco",
      "Hyundai",
      "Kodak",
      "LG",
      "Toshiba",
      "TCL",
      "Hisense",
      "Onida",
      "Amaze1",
      "SANSUI",
      "OnePlus",
      "Redmi",
    ],
  },
];

export const sortList = ["Popular", "Price: Low to High", "Price: High to Low"];
